version: '3'
services:
  # PostgreSQL
  postgres_db:
    container_name: postgres_db
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    # M1チップでも動作するように設定（Intel Macの場合でも動作可）
    platform: linux/x86_64
    env_file: ./docker.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # ヘルスチェック
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
 
  # Django REST framework
  backend:
    container_name: DRF
    env_file: ./docker.env.prod
    build:
      context: .
      dockerfile: containers/drf/Dockerfile
    # 8000番ポートをNginx側から接続できるように開く
    expose:
      - "8000"
    # シェルスクリプト実行
    command: sh -c "/usr/local/bin/entrypoint.sh"
    volumes:
      - .:/code
      - ./static:/code/static
    depends_on:
      postgres_db:
        condition: service_healthy

  web:
    container_name: nginx
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
     - ./static:/code/static
    depends_on:
      - backend

volumes:
  postgres_data:
  static: